-- =====================================================
-- Decimal.Health Competitive Intelligence Agent
-- Database Schema for Supabase
-- All tables prefixed with dh_ for namespace isolation
-- =====================================================

-- Enable UUID extension
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- =====================================================
-- ENUM TYPES
-- =====================================================

CREATE TYPE dh_signal_type AS ENUM (
  'NEW_OFFERING',
  'CLIENT_WIN',
  'THOUGHT_LEADERSHIP',
  'TALENT_MOVE',
  'PARTNERSHIP',
  'ACQUISITION',
  'EVENT_PRESENCE',
  'PRICING_SIGNAL',
  'REGULATORY_COMMENT',
  'CAPABILITY_SHIFT'
);

CREATE TYPE dh_urgency_level AS ENUM (
  'critical',
  'high',
  'medium',
  'low'
);

-- =====================================================
-- TABLE: dh_competitors
-- Master record for each tracked competitor
-- =====================================================

CREATE TABLE dh_competitors (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  name TEXT NOT NULL UNIQUE,
  segment_tier INTEGER NOT NULL CHECK (segment_tier BETWEEN 1 AND 5),
  segment_label TEXT NOT NULL,
  website_url TEXT NOT NULL,
  description TEXT NOT NULL DEFAULT '',
  offerings_overlap JSONB NOT NULL DEFAULT '[]',
  last_crawled_at TIMESTAMPTZ,
  profile_summary TEXT,
  logo_url TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_dh_competitors_tier ON dh_competitors(segment_tier);

-- =====================================================
-- TABLE: dh_signals
-- Individual intelligence signals with AI analysis
-- =====================================================

CREATE TABLE dh_signals (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  competitor_id UUID NOT NULL REFERENCES dh_competitors(id) ON DELETE CASCADE,
  signal_type dh_signal_type NOT NULL,
  source_url TEXT NOT NULL DEFAULT '',
  raw_content TEXT,
  processed_summary TEXT NOT NULL DEFAULT '',
  offering_tags JSONB NOT NULL DEFAULT '[]',
  urgency dh_urgency_level NOT NULL DEFAULT 'medium',
  strategic_assessment TEXT,
  detected_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  processed_at TIMESTAMPTZ
);

CREATE INDEX idx_dh_signals_competitor ON dh_signals(competitor_id);
CREATE INDEX idx_dh_signals_type ON dh_signals(signal_type);
CREATE INDEX idx_dh_signals_urgency ON dh_signals(urgency);
CREATE INDEX idx_dh_signals_detected ON dh_signals(detected_at DESC);

-- =====================================================
-- TABLE: dh_briefings
-- Weekly synthesis briefings generated by Claude
-- =====================================================

CREATE TABLE dh_briefings (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  period_start DATE NOT NULL,
  period_end DATE NOT NULL,
  briefing_content JSONB NOT NULL DEFAULT '{}',
  key_themes JSONB NOT NULL DEFAULT '[]',
  recommended_actions JSONB NOT NULL DEFAULT '[]',
  generated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_dh_briefings_period ON dh_briefings(period_end DESC);

-- =====================================================
-- TABLE: dh_crawl_history
-- Change detection tracking
-- =====================================================

CREATE TABLE dh_crawl_history (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  competitor_id UUID NOT NULL REFERENCES dh_competitors(id) ON DELETE CASCADE,
  source_type TEXT NOT NULL,
  url TEXT NOT NULL,
  content_hash TEXT,
  last_crawled_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  change_detected BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE INDEX idx_dh_crawl_competitor ON dh_crawl_history(competitor_id);

-- =====================================================
-- TABLE: dh_search_queries
-- Registry of SerpAPI queries
-- =====================================================

CREATE TABLE dh_search_queries (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  query_template TEXT NOT NULL,
  category TEXT NOT NULL,
  last_run_at TIMESTAMPTZ,
  results_count INTEGER NOT NULL DEFAULT 0
);

-- =====================================================
-- TABLE: dh_alerts
-- Alert delivery tracking
-- =====================================================

CREATE TABLE dh_alerts (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  signal_id UUID NOT NULL REFERENCES dh_signals(id) ON DELETE CASCADE,
  alert_type TEXT NOT NULL DEFAULT 'notification',
  delivered_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  delivery_channel TEXT NOT NULL DEFAULT 'dashboard',
  acknowledged_at TIMESTAMPTZ
);

CREATE INDEX idx_dh_alerts_signal ON dh_alerts(signal_id);
CREATE INDEX idx_dh_alerts_unacked ON dh_alerts(acknowledged_at) WHERE acknowledged_at IS NULL;

-- =====================================================
-- ROW LEVEL SECURITY
-- =====================================================

ALTER TABLE dh_competitors ENABLE ROW LEVEL SECURITY;
ALTER TABLE dh_signals ENABLE ROW LEVEL SECURITY;
ALTER TABLE dh_briefings ENABLE ROW LEVEL SECURITY;
ALTER TABLE dh_crawl_history ENABLE ROW LEVEL SECURITY;
ALTER TABLE dh_search_queries ENABLE ROW LEVEL SECURITY;
ALTER TABLE dh_alerts ENABLE ROW LEVEL SECURITY;

-- Allow read access
CREATE POLICY "dh_allow_read" ON dh_competitors FOR SELECT USING (true);
CREATE POLICY "dh_allow_read" ON dh_signals FOR SELECT USING (true);
CREATE POLICY "dh_allow_read" ON dh_briefings FOR SELECT USING (true);
CREATE POLICY "dh_allow_read" ON dh_crawl_history FOR SELECT USING (true);
CREATE POLICY "dh_allow_read" ON dh_search_queries FOR SELECT USING (true);
CREATE POLICY "dh_allow_read" ON dh_alerts FOR SELECT USING (true);

-- Allow insert/update (service role for pipelines)
CREATE POLICY "dh_allow_insert" ON dh_competitors FOR INSERT WITH CHECK (true);
CREATE POLICY "dh_allow_update" ON dh_competitors FOR UPDATE USING (true);
CREATE POLICY "dh_allow_insert" ON dh_signals FOR INSERT WITH CHECK (true);
CREATE POLICY "dh_allow_update" ON dh_signals FOR UPDATE USING (true);
CREATE POLICY "dh_allow_insert" ON dh_briefings FOR INSERT WITH CHECK (true);
CREATE POLICY "dh_allow_insert" ON dh_crawl_history FOR INSERT WITH CHECK (true);
CREATE POLICY "dh_allow_update" ON dh_crawl_history FOR UPDATE USING (true);
CREATE POLICY "dh_allow_insert" ON dh_search_queries FOR INSERT WITH CHECK (true);
CREATE POLICY "dh_allow_update" ON dh_search_queries FOR UPDATE USING (true);
CREATE POLICY "dh_allow_insert" ON dh_alerts FOR INSERT WITH CHECK (true);
CREATE POLICY "dh_allow_update" ON dh_alerts FOR UPDATE USING (true);
